management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: 'true'
      show-details: always
  info:
    env:
      enabled: 'true'
spring:
  cloud:
    gateway:
      routes[0]:
        id: employee-service
        uri: lb://employee-service
        predicates[0]: Path=/api/v1/employee/**
      routes[1]:
        id: department-service
        predicates[0]: Path=/api/v1/department/**
        uri: lb://department-service
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: 'true'
  instance:
    appname: api-gateway
server:
  port: '9191'
