spring:
  application:
    name: employee-service

  config:
    import:
    - "optional:configserver:http://localhost:8888"

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "heath,info,circuitbreakers"
    
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      employee-service:
        register-health-indicator: true
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

  retry:
    instances:
      employee-service:
        max-attempts: 3
        wait-duration: 2s
        